// Generated by Selenium IDE
package edu.pitt.cs;

import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;
import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless");
    driver = new ChromeDriver(options);
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void tEST1LINKS() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div/header/nav/ul/li[8]/a")));
    }
    {
      WebElement element = driver.findElement(By.xpath("/html/body/div/header/nav/ul/li[8]/a"));
      String attribute = element.getAttribute("href");
      vars.put("reset", attribute);
    }
    assertEquals("http://localhost:8080/reset", vars.get("reset").toString());
  }

  @Test
  public void tEST2RESET() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=true\";document.cookie = \"2=true\";document.cookie = \"3=true\";");
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Reset")));
    }
    driver.findElement(By.linkText("Reset")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div/main/div[1]/div/ul")));
    }
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[1]")).getText(),
        is("ID 1. Jennyanydots"));
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[2]")).getText(),
        is("ID 2. Old Deuteronomy"));
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[3]")).getText(),
        is("ID 3. Mistoffelees"));
  }

  @Test
  public void tEST3CATALOG() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Catalog")));
    }
    driver.findElement(By.linkText("Catalog")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div/main/div[1]/ol/li[2]/img")));
    }
    {
      WebElement element = driver.findElement(By.xpath("/html/body/div/main/div[1]/ol/li[2]/img"));
      String attribute = element.getAttribute("src");
      vars.put("catTwoSrc", attribute);
    }
    assertEquals(vars.get("catTwoSrc").toString(), "http://localhost:8080/images/cat2.jpg");
  }

  @Test
  public void tEST4LISTING() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Catalog")));
    }
    driver.findElement(By.linkText("Catalog")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div/main/div[1]/div/ul")));
    }
    vars.put("catCount", driver.findElements(By.xpath("/html/body/div/main/div[1]/div/ul/li")).size());
    assertEquals(vars.get("catCount").toString(), "3");
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div/main/div[1]/div/ul/li[3]")));
    }
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[3]")).getText(),
        is("ID 3. Mistoffelees"));
  }

  @Test
  public void tEST5RENTACAT() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(
          ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div/main/div[1]/div[2]/div[3]/button")));
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("/html/body/div/main/div[1]/div[2]/div[3]/button"));
      assert (elements.size() > 0);
    }
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(
          ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div/main/div[1]/div[3]/div[3]/button")));
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("/html/body/div/main/div[1]/div[3]/div[3]/button"));
      assert (elements.size() > 0);
    }
  }

  @Test
  public void tEST6RENT() {
    driver.get("http://localhost:8080/");
    // js.executeScript("document.cookie = \"1=false\";document.cookie =
    // \"2=false\";document.cookie = \"3=false\";");
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Rent-A-Cat")));
    }
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("rentID")));
    }
    driver.findElement(By.id("rentID")).click();
    driver.findElement(By.id("rentID")).sendKeys("1");
    driver.findElement(By.cssSelector(".form-group:nth-child(3) .btn")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("rentResult")));
    }
    assertThat(driver.findElement(By.id("rentResult")).getText(), is("Success!"));
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[1]")).getText(), is("Rented out"));
  }

  @Test
  public void tEST7RETURN() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=true\";document.cookie = \"3=false\";");
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Rent-A-Cat")));
    }
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("returnID")));
    }
    driver.findElement(By.id("returnID")).click();
    driver.findElement(By.id("returnID")).sendKeys("2");
    driver.findElement(By.cssSelector(".form-group:nth-child(4) .btn")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("returnResult")));
    }
    assertThat(driver.findElement(By.id("returnResult")).getText(), is("Success!"));
  }

  @Test
  public void tEST8FEEDACAT() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Feed-A-Cat")));
    }
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(
          ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div/main/div[1]/div[2]/div[3]/button")));
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("/html/body/div/main/div[1]/div[2]/div[3]/button"));
      assert (elements.size() > 0);
    }
  }

  @Test
  public void tEST9FEED() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Feed-A-Cat")));
    }
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    driver.findElement(By.id("catnips")).click();
    driver.findElement(By.id("catnips")).sendKeys("6");
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".btn")));
    }
    driver.findElement(By.cssSelector(".btn")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.textToBe(By.id("feedResult"), "Nom, nom, nom."));
    }
    assertThat(driver.findElement(By.id("feedResult")).getText(), is("Nom, nom, nom."));
  }

  @Test
  public void tEST10GREETACAT() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Greet-A-Cat")));
    }
    driver.findElement(By.linkText("Greet-A-Cat")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div/main/div[1]/div[2]/h4")));
    }
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div[2]/h4")).getText(), is("Meow!Meow!Meow!"));
  }

  @Test
  public void tEST11GREETACATWITHNAME() {
    driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div/main/div[1]/div[2]/h4")));
    }
    assertThat(driver.findElement(By.xpath("/html/body/div/main/div[1]/div[2]/h4")).getText(),
        is("Meow! from Jennyanydots."));
  }
  // @Test
  // public void dEFECT1FEEDACAT0() {
  // driver.get("https://cs1632.appspot.com/");
  // driver.manage().window().setSize(new Dimension(813, 727));
  // driver.findElement(By.linkText("Feed-A-Cat")).click();
  // {
  // List<WebElement> elements = driver.findElements(By.id("catnips"));
  // assert(elements.size() > 0);
  // }
  // driver.findElement(By.id("catnips")).click();
  // driver.findElement(By.id("catnips")).sendKeys("0");
  // driver.findElement(By.cssSelector(".btn")).click();
  // {
  // WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
  // wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\'feedResult\'
  // and text()=\'Nom, nom, nom.\']")));
  // }
  // assertThat(driver.findElement(By.id("feedResult")).getText(), is("failure"));
  // }
  // @Test
  // public void dEFECT2FUNRENTFEEDNOCATS() {
  // driver.get("https://cs1632.appspot.com/");
  // driver.manage().window().setSize(new Dimension(813, 727));
  // js.executeScript("document.cookie = \"1=true\";document.cookie =
  // \"2=true\";document.cookie = \"3=true\";");
  // driver.findElement(By.linkText("Rent-A-Cat")).click();
  // {
  // WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
  // wait.until(ExpectedConditions.presenceOfElementLocated(By.id("rentID")));
  // }
  // driver.findElement(By.id("rentID")).click();
  // driver.findElement(By.id("rentID")).sendKeys("1");
  // driver.findElement(By.cssSelector(".form-group:nth-child(3) .btn")).click();
  // {
  // WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
  // wait.until(ExpectedConditions.presenceOfElementLocated(By.id("rentID")));
  // }
  // driver.findElement(By.id("rentID")).click();
  // driver.findElement(By.id("rentID")).sendKeys("2");
  // driver.findElement(By.cssSelector(".form-group:nth-child(3) .btn")).click();
  // {
  // WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
  // wait.until(ExpectedConditions.presenceOfElementLocated(By.id("rentID")));
  // }
  // driver.findElement(By.id("rentID")).click();
  // driver.findElement(By.id("rentID")).sendKeys("3");
  // driver.findElement(By.cssSelector(".form-group:nth-child(3) .btn")).click();
  // driver.findElement(By.linkText("Feed-A-Cat")).click();
  // {
  // WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
  // wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//input[@id=\'catnips\']")));
  // }
  // driver.findElement(By.xpath("//input[@id=\'catnips\']")).click();
  // driver.findElement(By.id("catnips")).sendKeys("6");
  // driver.findElement(By.cssSelector(".btn")).click();
  // {
  // WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
  // wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\'feedResult\'
  // and text()=\'Cat fight!\']")));
  // }
  // assertThat(driver.findElement(By.xpath("//*[@id=\'feedResult\' and
  // text()=\'Cat fight!\']")).getText(), is("failure"));
  // }
  // @Test
  // public void dEFECT3FEEDACATNEGATIVE() {
  // driver.get("https://cs1632.appspot.com/");
  // driver.manage().window().setSize(new Dimension(813, 727));
  // driver.findElement(By.linkText("Feed-A-Cat")).click();
  // {
  // List<WebElement> elements = driver.findElements(By.id("catnips"));
  // assert(elements.size() > 0);
  // }
  // driver.findElement(By.id("catnips")).click();
  // driver.findElement(By.id("catnips")).sendKeys("-3");
  // driver.findElement(By.cssSelector(".btn")).click();
  // {
  // WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
  // wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\'feedResult\'
  // and text()=\'Nom, nom, nom.\']")));
  // }
  // assertThat(driver.findElement(By.id("feedResult")).getText(), is("failure"));
  // }
}
